# Generated by Django 2.2.9 on 2020-01-06 23:18

from django.db import migrations, models
import uploading.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='', upload_to=uploading.models.upload_media_file)),
            ],
        ),
    ]
